# Generated by Django 4.1.5 on 2023-02-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincust', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titile',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='cat',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
